In [79]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [81]:
df = pd.read_csv(r"C:\Users\Lenovo\Desktop\intern project 2\Cleaned\preprocessed_policy_dataset.csv")

df.head(100)

,policy_text,policy_area,public_sentiment,impact_label,processed_text
0,Small procedural adjustments were made in the ...,public safety,Negative,Low Impact,small procedural adjustment made management pu...
1,The central government introduces a large-scal...,digital governance,Neutral,High Impact,central government introduces largescale initi...
2,Small procedural adjustments were made in the ...,digital governance,Negative,Low Impact,small procedural adjustment made management di...
3,The policy updates documentation rules related...,agriculture,Neutral,Low Impact,policy update documentation rule related agric...
4,Local authorities revised guidelines for handl...,public safety,Negative,Low Impact,local authority revised guideline handling pub...
...,...,...,...,...,...
95,The central government introduces a large-scal...,employment,Positive,High Impact,central government introduces largescale initi...
96,Minor administrative changes were introduced i...,social welfare,Negative,Low Impact,minor administrative change introduced local s...
97,The government launches a nationwide employmen...,employment,Positive,High Impact,government launch nationwide employment reform...
98,A comprehensive reform significantly improves ...,health,Neutral,High Impact,comprehensive reform significantly improves pu...
99,The policy updates documentation rules related...,social welfare,Negative,Low Impact,policy update documentation rule related socia...

In [82]:
df.shape

(20000, 5)

In [83]:
df["impact_label"].value_counts()

impact_label
Low Impact     10026
High Impact     9974
Name: count, dtype: int64

In [84]:
df.drop_duplicates(subset=["processed_text"])

,policy_text,policy_area,public_sentiment,impact_label,processed_text
0,Small procedural adjustments were made in the ...,public safety,Negative,Low Impact,small procedural adjustment made management pu...
1,The central government introduces a large-scal...,digital governance,Neutral,High Impact,central government introduces largescale initi...
2,Small procedural adjustments were made in the ...,digital governance,Negative,Low Impact,small procedural adjustment made management di...
3,The policy updates documentation rules related...,agriculture,Neutral,Low Impact,policy update documentation rule related agric...
4,Local authorities revised guidelines for handl...,public safety,Negative,Low Impact,local authority revised guideline handling pub...
...,...,...,...,...,...
259,The central government introduces a large-scal...,environment,Positive,High Impact,central government introduces largescale initi...
311,A new national policy improves access to socia...,social welfare,Positive,High Impact,new national policy improves access social wel...
336,The central government introduces a large-scal...,transport,Positive,High Impact,central government introduces largescale initi...
418,A routine regulation modifies internal operati...,environment,Neutral,Low Impact,routine regulation modifies internal operation...
805,A new national policy improves access to healt...,health,Positive,High Impact,new national policy improves access health ser...

In [85]:
X_text = df["processed_text"]

In [86]:
vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(X_text)

print("Feature matrix shape:", X.shape)

Feature matrix shape: (20000, 71)

In [87]:
feature_names = vectorizer.get_feature_names_out()

X_df = pd.DataFrame(X.toarray(), columns=feature_names)

X_df.head()

,access,across,adjustment,administrative,affecting,agriculture,authority,central,change,citizen,...,sector,service,significantly,small,social,state,transport,update,urban,welfare
0,0.0,0.0,0.370446,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.370446,0.0,0.0,0.0,0.00000,0.0,0.0
1,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.362899,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0
2,0.0,0.0,0.362979,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.362979,0.0,0.0,0.0,0.00000,0.0,0.0
3,0.0,0.0,0.000000,0.0,0.0,0.387871,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.38828,0.0,0.0
4,0.0,0.0,0.000000,0.0,0.0,0.000000,0.370069,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0

In [88]:
final_dataset = pd.concat(
    [
        X_df,
        df[["policy_area", "public_sentiment", "impact_label"]].reset_index(drop=True)
    ],
    axis=1
)

final_dataset.head()

,access,across,adjustment,administrative,affecting,agriculture,authority,central,change,citizen,...,small,social,state,transport,update,urban,welfare,policy_area,public_sentiment,impact_label
0,0.0,0.0,0.370446,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.370446,0.0,0.0,0.0,0.00000,0.0,0.0,public safety,Negative,Low Impact
1,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.362899,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0,digital governance,Neutral,High Impact
2,0.0,0.0,0.362979,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.362979,0.0,0.0,0.0,0.00000,0.0,0.0,digital governance,Negative,Low Impact
3,0.0,0.0,0.000000,0.0,0.0,0.387871,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.38828,0.0,0.0,agriculture,Neutral,Low Impact
4,0.0,0.0,0.000000,0.0,0.0,0.000000,0.370069,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.00000,0.0,0.0,public safety,Negative,Low Impact

In [ ]:
final_dataset.to_csv(r"C:\Users\Lenovo\Desktop\intern project 2\Processed Data\feature_engineered_dataset.csv", index=False)

print("Feature engineered dataset saved successfully")