In [2]:
import pandas as pd
import nltk
import re

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to C:\Users\Mohammed
[nltk_data]     Yaseer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to C:\Users\Mohammed
[nltk_data]     Yaseer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to C:\Users\Mohammed
[nltk_data]     Yaseer\AppData\Roaming\nltk_data...

True

In [6]:
df = pd.read_csv(r"C:\Users\Mohammed Yaseer\Desktop\project2\cleaned\cleaned_policy_dataset.csv")

df.head(100)

,policy_text,policy_area,public_sentiment,impact_label
0,Small procedural adjustments were made in the ...,public safety,Negative,Low Impact
1,The central government introduces a large-scal...,digital governance,Neutral,High Impact
2,Small procedural adjustments were made in the ...,digital governance,Negative,Low Impact
3,The policy updates documentation rules related...,agriculture,Neutral,Low Impact
4,Local authorities revised guidelines for handl...,public safety,Negative,Low Impact
...,...,...,...,...
95,The central government introduces a large-scal...,employment,Positive,High Impact
96,Minor administrative changes were introduced i...,social welfare,Negative,Low Impact
97,The government launches a nationwide employmen...,employment,Positive,High Impact
98,A comprehensive reform significantly improves ...,health,Neutral,High Impact
99,The policy updates documentation rules related...,social welfare,Negative,Low Impact

In [7]:
df.shape

(20000, 4)

In [8]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r'[^a-zA-Z\s]', '', text)

    words = word_tokenize(text)

    words = [w for w in words if w not in stop_words]

    words = [lemmatizer.lemmatize(w) for w in words]

    return " ".join(words)

In [10]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to C:\Users\Mohammed
[nltk_data]     Yaseer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Mohammed
[nltk_data]     Yaseer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Mohammed
[nltk_data]     Yaseer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Mohammed
[nltk_data]     Yaseer\AppData\Roaming\nltk_data...

True

In [11]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to C:\Users\Mohammed
[nltk_data]     Yaseer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [12]:
df["processed_text"] = df["policy_text"].apply(clean_text)

In [13]:
df.head()

,policy_text,policy_area,public_sentiment,impact_label,processed_text
0,Small procedural adjustments were made in the ...,public safety,Negative,Low Impact,small procedural adjustment made management pu...
1,The central government introduces a large-scal...,digital governance,Neutral,High Impact,central government introduces largescale initi...
2,Small procedural adjustments were made in the ...,digital governance,Negative,Low Impact,small procedural adjustment made management di...
3,The policy updates documentation rules related...,agriculture,Neutral,Low Impact,policy update documentation rule related agric...
4,Local authorities revised guidelines for handl...,public safety,Negative,Low Impact,local authority revised guideline handling pub...

In [14]:
clean_text(df["policy_text"].iloc[0])

'small procedural adjustment made management public safety program'

In [15]:
vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df["processed_text"])

In [16]:
X.shape

(20000, 71)

In [17]:
df.to_csv(r"C:\Users\Mohammed Yaseer\Desktop\project2\Processed data\preprocessed_policy_dataset.csv", index=False)

In [ ]:

import os
print("✅ File saved at:")
print(os.getcwd())

✅ File saved at:

NameError: name 'os' is not defined